### ISSUE TITLE
建议在根目录增加一个图片清单，方便脚本切换图片

### ISSUE THREAD

**Issue by gchuyun** [myseil/BingWallpaper#1]
比如：
2022-01-01/aaaa.jpg
2022-01-01/bbb.jpg

**Comment by myseil** [comment]
> 比如： 2022-01-01/aaaa.jpg 2022-01-01/bbb.jpg

不会考虑做索引，毕竟这个如果要收集的话还是挺简单的，一个小小python程序定时运行就可以了！

**Comment by EdNovas** [comment]
> 比如： 2022-01-01/aaaa.jpg 2022-01-01/bbb.jpg

https://api.ednovas.xyz/bing_paths.txt
做了个每日更新的txt列表，应该符合你的要求
