### ISSUE TITLE
接口用法

### ISSUE THREAD

**Issue by KimiLLee** [myseil/BingWallpaper#2]
这个接口的用法我有些疑问，请教一下
1.日期的格式是yyyy-MM-dd吗

2.图片名应该如何书写
![@7T}243Z{@T1NH$FBDY78Q](https://github.com/myseil/BingWallpaper/assets/56219725/b57af707-13b3-414d-a475-287e923e49af)
这是我从源代码找到的文件名称
我这样写url：https://cdn.jsdelivr.net/gh/myseil/BingWallpaper/BingImage/2024-05-16/OHR.ReconquistaVigo
返回这个信息Package size exceeded the configured limit of 50 MB. Try https://github.com/myseil/BingWallpaper/tree/master/BingImage/2024-05-16/OHR.ReconquistaVigo instead.
请指点一下这图片名怎么写

**Comment by myseil** [comment]
我的是以这个api返回的json数据为准。https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=10&nc=1612409408851&pid=hp&FORM=BEHPTB&uhd=1&uhdwidth=3840&uhdheight=2160
